project1/views/main.py
"""
author:ljt
c_date:2021/1/23 14:44
u_date:2021/1/23 14:44
reversion:1.0
file_name:main

"""
from flask import render_template, Blueprint

book = {
    'name': '降龙十八掌',
    'author': '金庸',
    'articles': [
        {
            'id': '001',
            'title': '第一式:飞龙在天',
            'content': '气走督脉行手阳明大肠经商阳，二间，三间，合谷，阳溪，偏历，温溜，下廉，上廉，手三里，曲池，肘髎，手五里，臂臑，肩髃，巨骨，天鼎，扶突，口和髎，迎香.',
        },
        {
            'id': '002',
            'title': '第二式:见龙在田',
            'content': '提气凝神,运气与手少阳三焦经行 关冲液门中渚阳池外关支沟会宗三阳络四渎天井清冷渊消泺臑会肩髎天髎天牖翳风瘛脉颅息角孙耳门耳和髎丝竹空.返任脉停于掌心.',
        },
        {
            'id': '003',
            'title': '第三式:鸿渐于陆',
            'content': '气走浮郄委阳委中附分魄户膏肓神堂譩譆膈关魂门阳纲意舍胃仓肓门志室胞肓秩边合阳承筋承山.气凝会阴.',
        },
    ]
}

mainbp = Blueprint('main', __name__)


@mainbp.route('/')
def index():
    articles = book['articles']
    return render_template('index.html', **locals())


@mainbp.route('/<int:pk>')
def detail(pk):
    article = None
    for a in book['articles']:
        if int(a['id']) == pk:
            article = a
    return render_template('detail.html', **locals())

project1/views/user.py
"""
author:ljt
c_date:2021/1/23 14:44
u_date:2021/1/23 14:44
reversion:1.0
file_name:user

"""
from flask import request, redirect, render_template, url_for, session, flash, Blueprint

users = [
    {
        'email': '123456@qq.com',
        'password': '123456'
    }
]
userbp = Blueprint('user', __name__)


@userbp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html', **locals())
    elif request.method == 'POST':
        user = None
        email = request.form.get('email')
        password = request.form.get('password')
        for u in users:
            print(u['email'], u['password'], '=================')
            if u['email'] == email and u['password'] == password:
                session['user'] = email
                return redirect(url_for('main.index'))
        flash("用户名或者密码错误")
        return redirect(url_for('user.login'))


@userbp.route('/logout')
def logout():
    session.pop('user')
    return redirect(url_for('main.index'))


@userbp.route('/regist', methods=['GET', 'POST'])
def regist():
    if request.method == 'GET':
        return render_template('regist.html', **locals())
    elif request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        password2 = request.form.get('password2')
        for u in users:
            if u["email"] == email:
                flash("邮箱已经注册")
                return redirect(url_for('user.regist'))
        if password != password2:
            flash("密码不一致")
            return redirect(url_for('user.regist'))

        users.append({
            "email": email,
            "password": password
        })
        print(users, '+++++++++++++++++++')
        return redirect(url_for('user.login'))

project1/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>
        {% block title %}
        基础类
        {% endblock %}
    </title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
    <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/main.css') }}">
    {% block lib %}

    {% endblock %}
</head>

<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">
                <img src="{{ url_for('static',filename='/img/default.png') }}">
            </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">首页 <span class="sr-only">(current)</span></a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if 'user' in session %}
                <li><a href="#">{{ session['user'] }}</a></li>
                <li><a href="{{ url_for('user.logout') }}">退出</a></li>
                {% else %}
                <li><a href="{{ url_for('user.regist') }}">注册</a></li>
                <li><a href="{{ url_for('user.login') }}">登录</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block main %}

{% endblock %}

<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
</body>
</html>

project1/templates/detail.html
{% extends 'base.html' %}
{% block title %}
    详情页
{% endblock %}
{% block main %}
    <div class="container">
        <div class="panel panel-default ">
           <div class="panel-heading">
            <h3 class="panel-title">{{ article.title }}</h3>
           </div>
           <div class="panel-body">
            {{ article.content }}
           </div>
        </div>
        <a class="btn btn-default" href="/" role="button">返回</a>
    </div>

{% endblock %}

project1/templates/index.html
{% extends 'base.html' %}
{% block title %}
    首页
{% endblock %}
{% block main %}
    <div class="container">
        <div class="list-group">
            {% for a in articles %}
                {% if a== articles|first %}
                    <a href="/{{ a.id }}" class="list-group-item active">
                         {{ a.title }}
                    </a>
                {% else %}
                    <a href="/{{ a.id }}" class="list-group-item ">
                         {{ a.title }}
                    </a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

project1/templates/login.html
{% extends 'base.html' %}
{% block title %}
登录页
{% endblock %}
{% block main %}
<div class="container">
    <form class="form-horizontal" method="post" action="{{ url_for('user.login')}}">
        <div class="form-group">
        {% for error in get_flashed_messages() %}
        <p class="text-danger">{{ error }}</p>
        {% endfor %}
      </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">邮箱:</label>
            <div class="col-sm-10">
                <input name="email" required type="email" class="form-control" id="inputEmail3" placeholder="输入邮箱">
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">密码:</label>
            <div class="col-sm-10">
                <input name="password" required type="password" class="form-control" id="inputPassword3" placeholder="输入密码">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label>
                        <input type="checkbox"> 记住密码
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">登录</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

project1/templates/regist.html
{% extends 'base.html' %}
{% block title %}
注册页
{% endblock %}
{% block main %}
<div class="container">
    <form class="form-horizontal" method="post" action="{{ url_for('user.regist')}}">
        <div class="form-group">
        {% for error in get_flashed_messages() %}
        <p class="text-danger">{{error}}</p>
        {% endfor %}
      </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">邮箱:</label>
            <div class="col-sm-10">
                <input name="email" required type="email" class="form-control" id="inputEmail3" placeholder="输入邮箱">
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">密码:</label>
            <div class="col-sm-10">
                <input name="password" required type="password" class="form-control" id="inputPassword3"
                       placeholder="输入密码">
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword4" class="col-sm-2 control-label">确认密码:</label>
            <div class="col-sm-10">
                <input name="password2" required type="password" class="form-control" id="inputPassword4"
                       placeholder="再次输入密码">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">注册</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}